[phases.setup]
# Node 22 to satisfy Angular 20 requirements
packages = ["nodejs-22_x"]

[phases.install]
commands = ["npm install"]

[phases.build]
commands = ["ng build rohan && ng run rohan:server"]

[phases.start]
commands = ["node dist/rohan/server/server.mjs"]

[environment]
PORT = "4000"
NODE_ENV = "production"
