[phases.setup]
# Use Node 22
packages = ["nodejs-22_x"]

[phases.install]
commands = ["npm install"]

[phases.build]
commands = ["npm run build:ssr:rohan"]

[phases.start]
commands = ["npm run serve:ssr:rohan"]

[environment]
PORT = "4000"
NODE_ENV = "production"
