[phases.setup]
packages = ["nodejs-20_x"]

[phases.setup]
packages = ["nodejs", "npm"]

[phases.install]
commands = ["npm install"]

[phases.build]
commands = ["npm run build"]

[phases.start]
commands = ["npm run serve:ssr:rohan"]

[environment]
PORT = "4000"
NODE_ENV = "production"
